name : "Step 1"

on :
  workflow_dispatch:
  push: 
    branches: 
      - main

permissions: read-all

jobs:
  new-job:
    name: new job
    permissions: write-all|read-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test of the code
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: python add.py
      - name: Create Sucess Issue
        uses: ManojCSE17/open-issue@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Vous avez Reuissi le Step 1
          body: FÃ©licitation! vous avez reuissi votre premier push complet sur le repository


        
    

 
  

